FROM node:16-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
ENV PORT 5000
ENV NODE_ENV production

COPY package.json ./
COPY package-lock.json ./

RUN npm ci --silent

COPY . ./

EXPOSE 5000

CMD ["npm", "start"]

# docker build -f Dockerfile.prod -t mern-forum_backend:prod .
# docker run -it --rm -v ${PWD}/logs:/app/logs -p 5000:5000 mern-forum_backend:prod